techswitch-learners/whale-spotting-2022-apr

frontend/src/clients/externalApiClient.ts
We have created the external api request endpoints
=> WS-20: Create external api endpoints

frontend/src/clients/externalApiClient.ts
Removed small typos in 2 places
=> WP-23: Correct typos

backend/Controllers/SightingController.cs, backend/Models/Request/CreateSightingRequest.cs, backend/Models/Response/SightingResponse.cs, backend/Repositories/SightingRepo.cs, backend/Services/SightingService.cs
Endpoint for the sighting post
=> Ws 06 posting endpoint

frontend/src/clients/internalApiClient.ts, frontend/src/components/homepage/Home.tsx
Create functions for get all sightings list and get all species list.
=> WS-18: internal api client

backend/Controllers/SightingController.cs, backend/Repositories/SightingRepo.cs, backend/Services/SightingService.cs
Created a get endpoint for sighting and tested as well using dummy data.
=> Ww 04 get sighting endpoint

frontend/src/App.tsx
Change all the routes in App.tsx to be "exact" to avoid a bug that was
happening (I should have caught this before)
=> WS-00: Fix routing bug

backend/Controllers/SightingController.cs, backend/Repositories/SightingRepo.cs, backend/Services/SightingService.cs
- Create PATCH approve sighting endpoint in SightingController
=> WS-10: Approve sighting endpoint

frontend/src/clients/internalApiClient.ts
Add method for an individual sighting from internal api
=> WS-33: Create fetchSightingById in internalApiClient.ts

backend/Controllers/SightingController.cs, backend/Repositories/SightingRepo.cs, backend/Services/SightingService.cs
We have made a Delete Sighting endpoint.
=> WW-11: delete sighting endpoint

backend/Controllers/SightingController.cs, backend/Repositories/SightingRepo.cs, backend/Services/SightingService.cs
Created get endpoints for approved and unapproved sightings and add the authorization header in unapproved sighting method.
=> WS-36: Created-endpoint-for-approved-unapproved-sightings

frontend/src/tests/loginpage/LoginForm.test.tsx, frontend/src/tests/loginpage/LoginPage.test.tsx
Create tests for LoginPage and LoginForm components
=> WS-39: Login Page tests

frontend/src/components/createsighting/CreateSightingForm.tsx
Now able to submit decimals in form
=> Ws 43 sighting form issue

backend/Repositories/SightingRepo.cs
Ensure the sighting repo methods do not return deleted sightings, and
also perform minor cleanups in that file
=> WS-00: SightingRepo clean up

frontend/public/index.html, frontend/src/App.tsx, frontend/src/components/login/LoginForm.scss, frontend/src/components/login/LoginForm.tsx, frontend/src/components/login/LoginPage.tsx, frontend/src/index.scss
Centered log in form and gave it responsive width
=> WS-47: Make login page desktop friendly

frontend/src/components/navbar/Navbar.tsx, frontend/src/tests/loginpage/LoginForm.test.tsx
The login function in the context was throwing a small error due to the return type so we just changed the return type of the mock function.
=> WS-56: Changing the login return type on mock function

frontend/src/components/navbar/Navbar.tsx
Nav closes and opens now after clicking on a link
=> WS-53: Add spans with toggle and target to close nav

frontend/src/components/login/LoginForm.tsx, frontend/src/index.scss
Add background linear gradient to log in page using colour scheme
=> WS-54: Add background colour to login page

frontend/src/components/createsighting/CreateSightingForm.tsx, frontend/src/components/createsighting/Sightingform.scss
Added styling to sighting form.
=> Ws 50 add styling to sighting form page

frontend/src/components/navbar/Navbar.tsx
Just a few tweaks of the navbar so it has a better layout
=> Ws 59 update navbar layout

frontend/src/clients/externalApiClient.ts
Change over the external API URLs to use HTTPS instead of HTTP
=> WS-00: Fix external API

backend/Controllers/SightingController.cs, backend/Services/AuthService.cs
Improve error handling for approveSighting endpoint error handling
=> WS-32: Tidy up approveSighting endpoint error handling

frontend/src/components/navbar/Navbar.tsx, frontend/src/components/sightingCard/sightingCard.tsx, frontend/src/components/unapprovedSightings/UnapprovedSightingPage.tsx
Add little bit styling on approve and delete buttons on unapproved sighting page.
=> Ws-65: Add styling on buttons

frontend/src/components/homepage/BinocularMarker.tsx
Allowing an unknown species to appear on the map
=> Ws 67 allow null species binoculars

frontend/src/components/navbar/Navbar.tsx
making sure the navbar autocloses and is aligned
=> WS-66: Adding alignment and auto close

frontend/src/clients/internalApiClient.ts
=> WS-63: Fixed delete sighting url

frontend/src/components/sightings/sightings.scss, frontend/src/components/sightings/sightings.tsx
Jordan was unhappy with the styling, so we changed it to match unapproved sightings page
=> WS-68: Added styling to sightings page
